"""
Preprocessing and Feature Engineering Module for Energy Consumption Pipeline.

Includes data cleaning, temporal feature extraction, lag and rolling statistics,
and strict data leakage prevention mechanisms.
"""

import os
import yaml
import numpy as np
import pandas as pd
from src.data_loader import load_raw_data, load_config


def preprocess_data(config_path: str = "configs/config.yaml") -> pd.DataFrame:
    """
    Load raw data, perform data validation, generate calendar, cyclical, lag,
    and rolling features, and save the processed dataframe.

    Returns:
        pd.DataFrame: Cleaned and feature-engineered dataset.
    """
    config = load_config(config_path)
    target_col = config["data"]["target_column"]
    datetime_col = config["data"]["datetime_column"]
    processed_dir = config["data"]["processed_dir"]
    processed_filename = config["data"]["processed_filename"]
    lags = config["feature_engineering"]["lags"]
    rolling_windows = config["feature_engineering"]["rolling_windows"]

    # 1. Load raw data
    df = load_raw_data(config_path)

    # 2. Chronological Sorting & Datetime Parsing
    df[datetime_col] = pd.to_datetime(df[datetime_col])
    df = df.sort_values(by=datetime_col).reset_index(drop=True)

    # 3. Data Integrity & Validation Checks
    initial_rows = len(df)
    df = df.drop_duplicates().reset_index(drop=True)
    dedup_rows = len(df)
    if initial_rows != dedup_rows:
        print(f"[INFO] Removed {initial_rows - dedup_rows} duplicate rows.")

    # 4. Feature Engineering: Calendar Features
    df["hour"] = df[datetime_col].dt.hour
    df["day_of_week"] = df[datetime_col].dt.dayofweek
    df["month"] = df[datetime_col].dt.month
    df["day"] = df[datetime_col].dt.day
    df["is_weekend"] = df["day_of_week"].isin([5, 6]).astype(int)

    # Cyclical Encoding for time features
    df["sin_hour"] = np.sin(2 * np.pi * df["hour"] / 24.0)
    df["cos_hour"] = np.cos(2 * np.pi * df["hour"] / 24.0)
    df["sin_day_of_week"] = np.sin(2 * np.pi * df["day_of_week"] / 7.0)
    df["cos_day_of_week"] = np.cos(2 * np.pi * df["day_of_week"] / 7.0)

    # 5. Feature Engineering: Lag Features for Target
    for lag in lags:
        df[f"appliances_lag_{lag}"] = df[target_col].shift(lag)

    # 6. Feature Engineering: Rolling Statistics (STRICT DATA LEAKAGE PREVENTION)
    # Using shift(1) ensures rolling statistics use ONLY strictly past observations t-1, t-2, ...
    for window in rolling_windows:
        df[f"rolling_mean_{window}"] = df[target_col].shift(1).rolling(window=window).mean()

    # 7. Drop rows with NaNs generated by shifting/rolling
    df = df.dropna().reset_index(drop=True)
    print(f"[INFO] Dataset shape after feature engineering & NaN cleanup: {df.shape}")

    # 8. Save Processed Dataset
    os.makedirs(processed_dir, exist_ok=True)
    processed_path = os.path.join(processed_dir, processed_filename)
    df.to_csv(processed_path, index=False)
    print(f"[SUCCESS] Processed dataset saved to: {processed_path}")

    return df


def get_feature_target_split(df: pd.DataFrame, config_path: str = "configs/config.yaml"):
    """
    Separate features (X) and target (y) from processed dataframe.

    Returns:
        X (pd.DataFrame): Feature columns
        y (pd.Series): Target vector
        feature_names (list): List of feature column names
    """
    config = load_config(config_path)
    target_col = config["data"]["target_column"]
    datetime_col = config["data"]["datetime_column"]

    # Exclude datetime column and target from feature matrix X
    exclude_cols = [datetime_col, target_col, "rv1", "rv2"]
    feature_cols = [col for col in df.columns if col not in exclude_cols]

    X = df[feature_cols]
    y = df[target_col]

    return X, y, feature_cols


def chronological_split(X: pd.DataFrame, y: pd.Series, train_ratio: float = 0.8):
    """
    Perform chronological (time-based) train-test split to prevent temporal data leakage.
    DO NOT SHUFFLE.
    """
    split_idx = int(len(X) * train_ratio)
    
    X_train, X_test = X.iloc[:split_idx], X.iloc[split_idx:]
    y_train, y_test = y.iloc[:split_idx], y.iloc[split_idx:]

    print(f"[INFO] Chronological Train-Test Split Completed:")
    print(f"       Train set size: {len(X_train)} samples ({train_ratio*100:.0f}%)")
    print(f"       Test set size:  {len(X_test)} samples ({(1-train_ratio)*100:.0f}%)")

    return X_train, X_test, y_train, y_test


if __name__ == "__main__":
    df_proc = preprocess_data()
    X, y, feature_names = get_feature_target_split(df_proc)
    X_tr, X_te, y_tr, y_te = chronological_split(X, y)
